wandb_version: 1

__is_set:
  desc: null
  value:
    wallet.hotkey: true
    axon.port: true
    logging.debug: true
wallet:
  desc: null
  value:
    name: default
    hotkey: validator
    path: ~/.bittensor/wallets/
axon:
  desc: null
  value:
    port: 8095
    ip: '[::]'
    external_port: null
    external_ip: null
    max_workers: 10
logging:
  desc: null
  value:
    debug: true
    trace: false
    record_log: false
    logging_dir: ~/.bittensor/miners
config:
  desc: null
  value: null
strict:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689867142.391502
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.11.3
      5: 0.15.5
      8:
      - 4
      - 5
