wandb_version: 1

__is_set:
  desc: null
  value:
    logging.trace: true
wallet:
  desc: null
  value:
    name: default
    hotkey: default
    path: ~/.bittensor/wallets/
axon:
  desc: null
  value:
    port: 8091
    ip: '[::]'
    external_port: null
    external_ip: null
    max_workers: 10
logging:
  desc: null
  value:
    debug: false
    trace: true
    record_log: false
    logging_dir: ~/.bittensor/miners
config:
  desc: null
  value: null
strict:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689871597.350691
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 15
      - 16
      - 23
      4: 3.11.3
      5: 0.15.5
      6: 4.30.2
      8:
      - 4
      - 5
